/** Allowlisted public tables/columns for admin CSV export. */

export type ExportableTableId =
  | "adoptable_cats"
  | "adoption_applications"
  | "adoption_locations"
  | "appointments"
  | "cats"
  | "clinic_fixes"
  | "clinics"
  | "community_partner_contacts"
  | "community_partners"
  | "disabled_volunteer_roles"
  | "dismissed_duplicate_pairs"
  | "help_requests"
  | "library_documents"
  | "platform_branding"
  | "profile_email_aliases"
  | "profiles"
  | "public_bookings"
  | "public_clinic_events"
  | "role_descriptions"
  | "saved_reports"
  | "shifts"
  | "team_announcements"
  | "trap_equipment_items"
  | "trap_teams"
  | "volunteer_applications"
  | "volunteer_hours"
  | "volunteer_role_requests";

export interface ExportableColumn {
  id: string;
  label: string;
}

export interface ExportableTable {
  id: ExportableTableId;
  label: string;
  columns: ExportableColumn[];
}

export const EXPORTABLE_TABLES: ExportableTable[] = [
  {
    id: "adoptable_cats",
    label: "Adoptable cats",
    columns: [
      { id: "id", label: "id" },
      { id: "name", label: "name" },
      { id: "age_description", label: "age description" },
      { id: "sex", label: "sex" },
      { id: "status", label: "status" },
      { id: "location_id", label: "location id" },
      { id: "spayed_neutered", label: "spayed neutered" },
      { id: "vaccinated", label: "vaccinated" },
      { id: "vaccination_notes", label: "vaccination notes" },
      { id: "fiv_status", label: "fiv status" },
      { id: "felv_status", label: "felv status" },
      { id: "fip_status", label: "fip status" },
      { id: "medical_notes", label: "medical notes" },
      { id: "personality_notes", label: "personality notes" },
      { id: "notes", label: "notes" },
      { id: "created_by_email", label: "created by email" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "profile_photo_url", label: "profile photo url" },
    ],
  },
  {
    id: "adoption_applications",
    label: "Adoption applications",
    columns: [
      { id: "id", label: "id" },
      { id: "status", label: "status" },
      { id: "cat_id", label: "cat id" },
      { id: "cat_interest_name", label: "cat interest name" },
      { id: "applicant_first_name", label: "applicant first name" },
      { id: "applicant_last_name", label: "applicant last name" },
      { id: "applicant_email", label: "applicant email" },
      { id: "applicant_phone", label: "applicant phone" },
      { id: "answers", label: "answers" },
      { id: "staff_notes", label: "staff notes" },
      { id: "additional_notes", label: "additional notes" },
      { id: "reviewed_by", label: "reviewed by" },
      { id: "reviewed_at", label: "reviewed at" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
    ],
  },
  {
    id: "adoption_locations",
    label: "Adoption locations",
    columns: [
      { id: "id", label: "id" },
      { id: "name", label: "name" },
      { id: "location_type", label: "location type" },
      { id: "contact_name", label: "contact name" },
      { id: "contact_phone", label: "contact phone" },
      { id: "contact_email", label: "contact email" },
      { id: "address", label: "address" },
      { id: "city", label: "city" },
      { id: "state", label: "state" },
      { id: "zip", label: "zip" },
      { id: "notes", label: "notes" },
      { id: "foster_profile_id", label: "foster profile id" },
      { id: "is_active", label: "is active" },
      { id: "created_by_email", label: "created by email" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
    ],
  },
  {
    id: "appointments",
    label: "Appointments",
    columns: [
      { id: "id", label: "id" },
      { id: "clinic_id", label: "clinic id" },
      { id: "clinic_name", label: "clinic name" },
      { id: "date", label: "date" },
      { id: "total_slots", label: "total slots" },
      { id: "reserved_slots", label: "reserved slots" },
      { id: "help_request_id", label: "help request id" },
      { id: "cat_id", label: "cat id" },
      { id: "reserved_by", label: "reserved by" },
      { id: "reserved_by_name", label: "reserved by name" },
      { id: "status", label: "status" },
      { id: "contact_name", label: "contact name" },
      { id: "contact_email", label: "contact email" },
      { id: "contact_phone", label: "contact phone" },
      { id: "cat_name", label: "cat name" },
      { id: "cat_colors", label: "cat colors" },
      { id: "cat_breed", label: "cat breed" },
      { id: "cat_gender", label: "cat gender" },
      { id: "transporter_name", label: "transporter name" },
      { id: "transporter_email", label: "transporter email" },
      { id: "transporter_phone", label: "transporter phone" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "clinic_result_logged_at", label: "clinic result logged at" },
      { id: "clinic_result_age_category", label: "clinic result age category" },
      { id: "clinic_result_gender", label: "clinic result gender" },
      { id: "clinic_result_logged_by", label: "clinic result logged by" },
      { id: "clinic_result_logged_by_name", label: "clinic result logged by name" },
    ],
  },
  {
    id: "cats",
    label: "Tracked cats",
    columns: [
      { id: "id", label: "id" },
      { id: "help_request_id", label: "help request id" },
      { id: "name", label: "name" },
      { id: "gender", label: "gender" },
      { id: "colors", label: "colors" },
      { id: "breed", label: "breed" },
      { id: "description", label: "description" },
      { id: "estimated_status", label: "estimated status" },
      { id: "trapped_status", label: "trapped status" },
      { id: "appointment_status", label: "appointment status" },
      { id: "appointment_id", label: "appointment id" },
      { id: "clinic_id", label: "clinic id" },
      { id: "clinic_name", label: "clinic name" },
      { id: "return_status", label: "return status" },
      { id: "foster_program", label: "foster program" },
      { id: "foster_name", label: "foster name" },
      { id: "foster_email", label: "foster email" },
      { id: "foster_phone", label: "foster phone" },
      { id: "trap_date", label: "trap date" },
      { id: "transport_date", label: "transport date" },
      { id: "return_date", label: "return date" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "microchip_id", label: "microchip id" },
      { id: "medical_notes", label: "medical notes" },
      { id: "age_category", label: "age category" },
      { id: "went_to_foster_facility", label: "went to foster facility" },
      { id: "foster_facility", label: "foster facility" },
      { id: "foster_facility_other", label: "foster facility other" },
      { id: "female_reproductive_status", label: "female reproductive status" },
    ],
  },
  {
    id: "clinic_fixes",
    label: "Clinic fixes",
    columns: [
      { id: "id", label: "id" },
      { id: "help_request_id", label: "help request id" },
      { id: "appointment_id", label: "appointment id" },
      { id: "age_category", label: "age category" },
      { id: "gender", label: "gender" },
      { id: "clinic_name", label: "clinic name" },
      { id: "fix_date", label: "fix date" },
      { id: "logged_by", label: "logged by" },
      { id: "logged_by_name", label: "logged by name" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
      { id: "went_to_foster_facility", label: "went to foster facility" },
      { id: "foster_facility", label: "foster facility" },
      { id: "foster_facility_other", label: "foster facility other" },
      { id: "cat_id", label: "cat id" },
    ],
  },
  {
    id: "clinics",
    label: "Clinics",
    columns: [
      { id: "id", label: "id" },
      { id: "name", label: "name" },
      { id: "address", label: "address" },
      { id: "phone", label: "phone" },
      { id: "operating_days", label: "operating days" },
      { id: "slots_per_day", label: "slots per day" },
      { id: "slots_by_day", label: "slots by day" },
      { id: "included_services", label: "included services" },
      { id: "packages", label: "packages" },
      { id: "addon_services", label: "addon services" },
      { id: "notes", label: "notes" },
      { id: "is_active", label: "is active" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "check_in_details", label: "check in details" },
      { id: "service_catalog", label: "service catalog" },
    ],
  },
  {
    id: "community_partner_contacts",
    label: "Community partner contacts",
    columns: [
      { id: "id", label: "id" },
      { id: "partner_id", label: "partner id" },
      { id: "name", label: "name" },
      { id: "title", label: "title" },
      { id: "email", label: "email" },
      { id: "phone", label: "phone" },
      { id: "notes", label: "notes" },
      { id: "is_primary", label: "is primary" },
      { id: "sort_order", label: "sort order" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
    ],
  },
  {
    id: "community_partners",
    label: "Community partners",
    columns: [
      { id: "id", label: "id" },
      { id: "name", label: "name" },
      { id: "organization_type", label: "organization type" },
      { id: "website", label: "website" },
      { id: "address", label: "address" },
      { id: "city", label: "city" },
      { id: "state", label: "state" },
      { id: "zip", label: "zip" },
      { id: "phone", label: "phone" },
      { id: "email", label: "email" },
      { id: "notes", label: "notes" },
      { id: "partnership_status", label: "partnership status" },
      { id: "is_active", label: "is active" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
    ],
  },
  {
    id: "disabled_volunteer_roles",
    label: "Disabled volunteer roles",
    columns: [
      { id: "role_id", label: "role id" },
      { id: "disabled_at", label: "disabled at" },
    ],
  },
  {
    id: "dismissed_duplicate_pairs",
    label: "Dismissed duplicate pairs",
    columns: [
      { id: "id", label: "id" },
      { id: "entity_type", label: "entity type" },
      { id: "left_id", label: "left id" },
      { id: "right_id", label: "right id" },
      { id: "dismissed_by", label: "dismissed by" },
      { id: "created_at", label: "created at" },
    ],
  },
  {
    id: "help_requests",
    label: "Cases (help requests)",
    columns: [
      { id: "id", label: "id" },
      { id: "contact_name", label: "Reporter full name" },
      { id: "contact_email", label: "Reporter email" },
      { id: "contact_phone", label: "Reporter phone" },
      { id: "colony_address", label: "colony address" },
      { id: "colony_city", label: "colony city" },
      { id: "colony_zip", label: "colony zip" },
      { id: "colony_county", label: "colony county" },
      { id: "kittens_under_8_weeks", label: "kittens under 8 weeks" },
      { id: "cats_over_8_weeks", label: "cats over 8 weeks" },
      { id: "colony_details_notes", label: "colony details notes" },
      { id: "can_help_trapping", label: "can help trapping" },
      { id: "has_traps_available", label: "has traps available" },
      { id: "can_transport_cats", label: "can transport cats" },
      { id: "has_recovery_space", label: "has recovery space" },
      { id: "consent_to_communications", label: "consent to communications" },
      { id: "status", label: "status" },
      { id: "priority", label: "priority" },
      { id: "internal_notes", label: "internal notes" },
      { id: "assigned_team", label: "assigned team" },
      { id: "assigned_to", label: "assigned to" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "case_number", label: "case number" },
      { id: "contact_first_name", label: "Reporter first name" },
      { id: "contact_last_name", label: "Reporter last name" },
      { id: "contact_street", label: "Reporter street" },
      { id: "contact_city", label: "Reporter city" },
      { id: "contact_state", label: "Reporter state" },
      { id: "contact_zip", label: "Reporter zip" },
      { id: "contact_county", label: "Reporter county" },
      { id: "colony_state", label: "colony state" },
      { id: "relationship_to_cats", label: "relationship to cats" },
      { id: "pregnant_count", label: "pregnant count" },
      { id: "feeding_cats", label: "feeding cats" },
      { id: "feeder_if_not", label: "Feeder note from intake" },
      { id: "trapping_experience", label: "trapping experience" },
      { id: "need_traps", label: "need traps" },
      { id: "willing_to_trap_transport", label: "willing to trap transport" },
      { id: "able_to_trap_transport", label: "able to trap transport" },
      { id: "how_heard", label: "how heard" },
      { id: "apartment_name", label: "Apartment / community" },
      { id: "resolution", label: "resolution" },
      { id: "closed_at", label: "closed at" },
      { id: "trapper_trap_loaner", label: "trapper trap loaner" },
      { id: "additional_notes", label: "additional notes" },
      { id: "outcome_tnvr_count", label: "outcome tnvr count" },
      { id: "outcome_acc_count", label: "outcome acc count" },
      { id: "outcome_foster_count", label: "outcome foster count" },
      { id: "outcome_other_count", label: "outcome other count" },
      { id: "cats_remaining", label: "cats remaining" },
      { id: "intake_notes", label: "intake notes" },
      { id: "outcome", label: "outcome" },
      { id: "closure_notes", label: "closure notes" },
      { id: "can_help", label: "can help" },
      { id: "has_traps", label: "has traps" },
      { id: "can_transport", label: "can transport" },
      { id: "consent_communications", label: "consent communications" },
      { id: "claimed_by_email", label: "Claimed by email" },
      { id: "claimed_by_name", label: "Claimed by volunteer name" },
      { id: "assigned_team_id", label: "assigned team id" },
      { id: "assigned_team_name", label: "Assigned team name" },
      { id: "follow_up_log", label: "follow up log" },
      { id: "follow_up_due_date", label: "follow up due date" },
      { id: "medical_flags", label: "medical flags" },
      { id: "medical_flag_dismissed", label: "medical flag dismissed" },
      { id: "medical_flag_forced", label: "medical flag forced" },
      { id: "history_log", label: "history log" },
      { id: "colony_lat", label: "colony lat" },
      { id: "colony_lng", label: "colony lng" },
      { id: "created_by", label: "created by" },
      { id: "feeder_name", label: "Colony feeder name" },
      { id: "feeder_phone", label: "Colony feeder phone" },
      { id: "feeder_email", label: "Colony feeder email" },
      { id: "feeder_street", label: "Colony feeder street" },
      { id: "feeder_city", label: "Colony feeder city" },
      { id: "feeder_state", label: "Colony feeder state" },
      { id: "feeder_zip", label: "Colony feeder zip" },
      { id: "feeder_county", label: "Colony feeder county" },
      { id: "feeder_lat", label: "Colony feeder lat" },
      { id: "feeder_lng", label: "Colony feeder lng" },
      { id: "reported_cats_over_8_weeks", label: "reported cats over 8 weeks" },
      { id: "reported_kittens_under_8_weeks", label: "reported kittens under 8 weeks" },
    ],
  },
  {
    id: "library_documents",
    label: "Library documents",
    columns: [
      { id: "id", label: "id" },
      { id: "title", label: "title" },
      { id: "description", label: "description" },
      { id: "file_url", label: "file url" },
      { id: "view_roles", label: "view roles" },
      { id: "is_active", label: "is active" },
      { id: "created_by_email", label: "created by email" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "section", label: "section" },
      { id: "body_markdown", label: "body markdown" },
    ],
  },
  {
    id: "platform_branding",
    label: "Platform branding",
    columns: [
      { id: "id", label: "id" },
      { id: "app_name", label: "app name" },
      { id: "logo_url", label: "logo url" },
      { id: "updated_at", label: "updated at" },
      { id: "updated_by", label: "updated by" },
      { id: "primary_color", label: "primary color" },
      { id: "sidebar_color", label: "sidebar color" },
      { id: "logo_light_url", label: "logo light url" },
      { id: "google_calendar_embed_url", label: "google calendar embed url" },
      { id: "intake_about_message", label: "colony request intro" },
      { id: "intake_donate_url", label: "colony donate url" },
      { id: "intake_donate_text", label: "colony donate button" },
    ],
  },
  {
    id: "profile_email_aliases",
    label: "Profile email aliases",
    columns: [
      { id: "id", label: "id" },
      { id: "profile_id", label: "profile id" },
      { id: "email", label: "email" },
      { id: "created_at", label: "created at" },
    ],
  },
  {
    id: "profiles",
    label: "User profiles",
    columns: [
      { id: "id", label: "id" },
      { id: "email", label: "email" },
      { id: "full_name", label: "full name" },
      { id: "phone", label: "phone" },
      { id: "role", label: "role" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "team_id", label: "team id" },
      { id: "volunteer_roles", label: "volunteer roles" },
      { id: "must_change_password", label: "must change password" },
      { id: "tnvr_certificate_uploaded", label: "tnvr certificate uploaded" },
      { id: "tnvr_certificate_url", label: "tnvr certificate url" },
      { id: "birthday", label: "birthday" },
      { id: "home_street", label: "home street" },
      { id: "home_city", label: "home city" },
      { id: "home_state", label: "home state" },
      { id: "home_zip", label: "home zip" },
      { id: "home_county", label: "home county" },
      { id: "platform_tutorial_completed_at", label: "platform tutorial completed at" },
      { id: "home_lat", label: "home lat" },
      { id: "home_lng", label: "home lng" },
      { id: "show_phone_in_directory", label: "show phone in directory" },
      { id: "show_address_in_directory", label: "show address in directory" },
      { id: "show_phone_on_hotspots_map", label: "show phone on hotspots map" },
      { id: "show_address_on_hotspots_map", label: "show address on hotspots map" },
      { id: "show_on_hotspots_map", label: "show on hotspots map" },
      { id: "show_email_in_directory", label: "show email in directory" },
    ],
  },
  {
    id: "public_bookings",
    label: "Public clinic bookings",
    columns: [
      { id: "id", label: "id" },
      { id: "event_id", label: "event id" },
      { id: "status", label: "status" },
      { id: "expires_at", label: "expires at" },
      { id: "contact_name", label: "contact name" },
      { id: "contact_email", label: "contact email" },
      { id: "contact_phone", label: "contact phone" },
      { id: "cat_name", label: "cat name" },
      { id: "cat_colors", label: "cat colors" },
      { id: "cat_breed", label: "cat breed" },
      { id: "cat_gender", label: "cat gender" },
      { id: "has_injuries", label: "has injuries" },
      { id: "injury_details", label: "injury details" },
      { id: "selected_addons", label: "selected addons" },
      { id: "total_price", label: "total price" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "hold_session_id", label: "hold session id" },
      { id: "addon_payments", label: "addon payments" },
    ],
  },
  {
    id: "public_clinic_events",
    label: "Public clinic events",
    columns: [
      { id: "id", label: "id" },
      { id: "clinic_id", label: "clinic id" },
      { id: "clinic_name", label: "clinic name" },
      { id: "title", label: "title" },
      { id: "date", label: "date" },
      { id: "location", label: "location" },
      { id: "total_spots", label: "total spots" },
      { id: "description", label: "description" },
      { id: "included_services", label: "included services" },
      { id: "addon_services", label: "addon services" },
      { id: "base_price", label: "base price" },
      { id: "cost_description", label: "cost description" },
      { id: "payment_url", label: "payment url" },
      { id: "is_active", label: "is active" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "pending_email_message", label: "pending email message" },
      { id: "confirmed_email_message", label: "confirmed email message" },
      { id: "service_catalog", label: "service catalog" },
      { id: "pricing_mode", label: "pricing mode" },
      { id: "pricing_matrix", label: "pricing matrix" },
    ],
  },
  {
    id: "role_descriptions",
    label: "Role descriptions",
    columns: [
      { id: "id", label: "id" },
      { id: "role_id", label: "role id" },
      { id: "label", label: "label" },
      { id: "description", label: "description" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "requirements", label: "requirements" },
      { id: "is_signup_active", label: "is signup active" },
    ],
  },
  {
    id: "saved_reports",
    label: "Saved reports",
    columns: [
      { id: "id", label: "id" },
      { id: "name", label: "name" },
      { id: "description", label: "description" },
      { id: "config", label: "config" },
      { id: "created_by", label: "created by" },
      { id: "created_by_email", label: "created by email" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
    ],
  },
  {
    id: "shifts",
    label: "Shifts",
    columns: [
      { id: "id", label: "id" },
      { id: "event_name", label: "event name" },
      { id: "shift_type", label: "shift type" },
      { id: "required_roles", label: "required roles" },
      { id: "date", label: "date" },
      { id: "start_time", label: "start time" },
      { id: "end_time", label: "end time" },
      { id: "location", label: "location" },
      { id: "team_ids", label: "team ids" },
      { id: "volunteers_needed", label: "volunteers needed" },
      { id: "signed_up_emails", label: "signed up emails" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "position_name", label: "position name" },
      { id: "waitlist_emails", label: "waitlist emails" },
      { id: "signup_mode", label: "signup mode" },
      { id: "declined_emails", label: "declined emails" },
    ],
  },
  {
    id: "team_announcements",
    label: "Team announcements",
    columns: [
      { id: "id", label: "id" },
      { id: "message", label: "message" },
      { id: "team_id", label: "team id" },
      { id: "team_name", label: "team name" },
      { id: "author_email", label: "author email" },
      { id: "author_name", label: "author name" },
      { id: "pinned", label: "pinned" },
      { id: "is_birthday", label: "is birthday" },
      { id: "birthday_person_name", label: "birthday person name" },
      { id: "comments", label: "comments" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "audience", label: "audience" },
      { id: "view_roles", label: "view roles" },
      { id: "team_ids", label: "team ids" },
    ],
  },
  {
    id: "trap_equipment_items",
    label: "Trap equipment",
    columns: [
      { id: "id", label: "id" },
      { id: "equipment_type", label: "equipment type" },
      { id: "description", label: "description" },
      { id: "quantity", label: "quantity" },
      { id: "status", label: "status" },
      { id: "team_id", label: "team id" },
      { id: "team_name", label: "team name" },
      { id: "location", label: "location" },
      { id: "notes", label: "notes" },
      { id: "logged_by_email", label: "logged by email" },
      { id: "logged_by_name", label: "logged by name" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "is_labeled", label: "is labeled" },
      { id: "equipment_label", label: "equipment label" },
      { id: "qr_code_data", label: "qr code data" },
      { id: "assigned_to_profile_id", label: "assigned to profile id" },
      { id: "borrower_name", label: "borrower name" },
      { id: "borrower_email", label: "borrower email" },
      { id: "borrower_phone", label: "borrower phone" },
    ],
  },
  {
    id: "trap_teams",
    label: "Trap teams",
    columns: [
      { id: "id", label: "id" },
      { id: "name", label: "name" },
      { id: "region", label: "region" },
      { id: "zip_codes", label: "zip codes" },
      { id: "members", label: "members" },
      { id: "lead_email", label: "lead email" },
      { id: "is_active", label: "is active" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
    ],
  },
  {
    id: "volunteer_applications",
    label: "Volunteer applications",
    columns: [
      { id: "id", label: "id" },
      { id: "email", label: "email" },
      { id: "phone", label: "phone" },
      { id: "location", label: "location" },
      { id: "roles", label: "roles" },
      { id: "certificate_url", label: "certificate url" },
      { id: "waiver_agreed", label: "waiver agreed" },
      { id: "policy_agreed", label: "policy agreed" },
      { id: "interests", label: "interests" },
      { id: "experience", label: "experience" },
      { id: "status", label: "status" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "birthday", label: "birthday" },
      { id: "full_name", label: "full name" },
      { id: "how_heard", label: "how heard" },
      { id: "liability_waiver_signed", label: "liability waiver signed" },
      { id: "policy_signed", label: "policy signed" },
      { id: "prior_experience", label: "prior experience" },
      { id: "roles_requested", label: "roles requested" },
      { id: "tnvr_certificate_uploaded", label: "tnvr certificate uploaded" },
      { id: "tnvr_certificate_url", label: "tnvr certificate url" },
      { id: "why_volunteer", label: "why volunteer" },
      { id: "availability", label: "availability" },
      { id: "admin_notes", label: "admin notes" },
      { id: "shadow_completed", label: "shadow completed" },
      { id: "intake_training", label: "intake training" },
      { id: "event_crash_course", label: "event crash course" },
      { id: "reviewed_by", label: "reviewed by" },
      { id: "reviewed_at", label: "reviewed at" },
      { id: "home_street", label: "home street" },
      { id: "home_city", label: "home city" },
      { id: "home_state", label: "home state" },
      { id: "home_zip", label: "home zip" },
      { id: "home_county", label: "home county" },
      { id: "imported_via_csv", label: "imported via csv" },
      { id: "user_requirements_completed_at", label: "user requirements completed at" },
      { id: "adoption_training", label: "adoption training" },
    ],
  },
  {
    id: "volunteer_hours",
    label: "Volunteer hours",
    columns: [
      { id: "id", label: "id" },
      { id: "volunteer_email", label: "volunteer email" },
      { id: "volunteer_name", label: "volunteer name" },
      { id: "team_id", label: "team id" },
      { id: "team_name", label: "team name" },
      { id: "date", label: "date" },
      { id: "hours", label: "hours" },
      { id: "hour_type", label: "hour type" },
      { id: "help_request_id", label: "help request id" },
      { id: "notes", label: "notes" },
      { id: "created_at", label: "created at" },
    ],
  },
  {
    id: "volunteer_role_requests",
    label: "Volunteer role requests",
    columns: [
      { id: "id", label: "id" },
      { id: "profile_id", label: "profile id" },
      { id: "application_id", label: "application id" },
      { id: "email", label: "email" },
      { id: "full_name", label: "full name" },
      { id: "requested_roles", label: "requested roles" },
      { id: "status", label: "status" },
      { id: "tnvr_certificate_uploaded", label: "tnvr certificate uploaded" },
      { id: "tnvr_certificate_url", label: "tnvr certificate url" },
      { id: "intake_training", label: "intake training" },
      { id: "shadow_completed", label: "shadow completed" },
      { id: "liability_waiver_signed", label: "liability waiver signed" },
      { id: "policy_signed", label: "policy signed" },
      { id: "event_crash_course", label: "event crash course" },
      { id: "admin_notes", label: "admin notes" },
      { id: "reviewed_by", label: "reviewed by" },
      { id: "reviewed_at", label: "reviewed at" },
      { id: "created_at", label: "created at" },
      { id: "updated_at", label: "updated at" },
      { id: "request_type", label: "request type" },
      { id: "adoption_training", label: "adoption training" },
    ],
  },
];

const TABLE_BY_ID = new Map(EXPORTABLE_TABLES.map((table) => [table.id, table]));

export function getExportableTable(id: string): ExportableTable | null {
  return TABLE_BY_ID.get(id as ExportableTableId) ?? null;
}

export function isExportableTableId(id: string): id is ExportableTableId {
  return TABLE_BY_ID.has(id as ExportableTableId);
}

/** Keep only allowlisted columns, preserving the request order. */
export function sanitizeExportColumns(tableId: string, requested: string[]): string[] | null {
  const table = getExportableTable(tableId);
  if (!table) return null;
  const allowed = new Set(table.columns.map((column) => column.id));
  const unique: string[] = [];
  for (const column of requested) {
    const id = column.trim();
    if (!id || !allowed.has(id) || unique.includes(id)) continue;
    unique.push(id);
  }
  return unique;
}

